# Headless service that allows us to get the IP addresses of our Cassandra nodes
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
    name: cassandra-peers
  name: cassandra-peers
spec:
  clusterIP: None
  ports:
    - port: 7000
      name: intra-node-communication
    - port: 7001
      name: tls-intra-node-communication
  selector:
    app: cassandra
