# A replication controller is responsible for replicating identical pods in a service.
apiVersion: v1
kind: ReplicationController
metadata:
  name: cassandra
  # The labels will be applied automatically
  # from the labels in the pod template, if not set
  # labels:
    # app: cassandra
  namespace: default
spec:
  replicas: 2
  # The selector will be applied automatically
  # from the labels in the pod template, if not set.
  # selector:
      # app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.5
          env:
            - name: PEER_DISCOVERY_SERVICE
              value: cassandra-peers
            - name: CASSANDRA_CLUSTER_NAME
              value: db1
            # - name: CASSANDRA_DC
              # value: dc1
              # value: europe-west1
            # - name: CASSANDRA_RACK
            #   value: rack1
            - name: CASSANDRA_ENDPOINT_SNITCH
              # value: GossipingPropertyFileSnitch
              value: GoogleCloudSnitch
            - name: CASSANDRA_NUM_TOKENS
              value: "256"
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            # - name: POD_NAMESPACE
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.namespace
            # - name: POD_IP
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: status.podIP
          image: eu.gcr.io/docker-practice/my_cassandra_image:v5.0.1
          name: cassandra
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
            # If you need it it is going away in C* 4.0
            #- containerPort: 9160
            #  name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}
